### ISSUE TITLE
Game stuck on PostInitilization: NEI Recipe Handlers

### ISSUE THREAD

**Issue by Mizzet5** [CraftedMods/nei-recipe-handlers#34]
I'm using a pretty big modpack with over 300 mods, including LotR and NEILotR. The game doesn't freeze, it just gets stuck on PostInitilization. Launcher logs indicate it's stuck on 'Checking LOTR lang file for updates zh_CN.lang'. I've waited upwards of 20 minutes but no luck. The other language files take around 1 minute each, by the way. I'm not sure which mod is at fault here but since it says NEI Recipe Handlers in-game I'm posting this here. I'm using the latest version of everything.

**Comment by CraftedMods** [comment]
Which version of NEI Recipe Handlers, NEI LOTR, and the LOTR Mod do you use? How would you describe your PC? Is it fast?
The language files have nothing to do with `neiRecipeHandlers`. The cause is probably the count of mods you have. NEI Recipe Handlers has to use some performance-intensive methods to compute some recipes of the LOTR Mod (because of the way they're coded), and the count of computations is related to the count of items that are registered. So with that many mods, it could be possible, that your PC just cannot handle the amount of computations. I can give you a more specific answer when I know your environment.

**Comment by jelaw21** [comment]
I had this same issue, but I muscled through it, and then when I selected a LOTR block to see the recipe, it crashed. 
neiLOTR-1.0.0-ALPHA
nerRecipeHandlers-2.0.2-ALPHA

Also installed:
NEI Addons  1.12.14.40
NEI Integration MC1.7.10.1.1.2

**Comment by CraftedMods** [comment]
Can you post the crash report?

**Comment by CraftedMods** [comment]
Probably related to #28.

**Comment by CraftedMods** [comment]
Feel free to reopen this.
