### ISSUE TITLE
Game freezes when staring up with  nei-recipe-handlers installed

### ISSUE THREAD

**Issue by ghost** [CraftedMods/nei-recipe-handlers#45]
![Capture](https://user-images.githubusercontent.com/34663132/82155190-b4f88d80-9838-11ea-9962-5da96e80a1e0.PNG)
[latest.log](https://github.com/CraftedMods/nei-recipe-handlers/files/4640662/latest.log)

**Comment by CraftedMods** [comment]
Startup can take five minutes (on slow machines or with many mods) or longer when new mods were updated or the game was started for the first time because of the LOTR alloy forge recipes. Subsequent startups are faster, because the results will be cached. If you don't want to wait that long, you've to disable the alloy forge recipe handlers via the configuration file of `neiRecipeHandlers`.

**Comment by ghost** [comment]
Is is supost to freeze and not respond? 

I don't think I captured that in my screenshot

**Comment by CraftedMods** [comment]
Hm, no. But I couldn't find anything suspicious in the logs, and I guess it really depends on your machine and the programs that run in parallel with MC.

**Comment by ghost** [comment]
Strange, I only had Discord in the background, I have an alright PC it takes about a minute or two to load in the game.

**Comment by CraftedMods** [comment]
Did you try to disable the alloy forges?

**Comment by ghost** [comment]
ya I think that fixed it

**Comment by CraftedMods** [comment]
With the new release of NEI LOTR (1.0.0-BETA), you can now configure the alloy forges to use hardcoded recipes, whic fixes that issue. This has to be enabled via the configuration file to take effect.
